[32mINFO[0m:     [14-05-2024 21:35:56] Set chroma_server_nofile to 65535
[32mINFO[0m:     [14-05-2024 21:35:56] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [14-05-2024 21:35:56] Starting component System
[36mDEBUG[0m:    [14-05-2024 21:35:56] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [14-05-2024 21:35:56] Starting component SqliteDB
[36mDEBUG[0m:    [14-05-2024 21:35:56] Starting component QuotaEnforcer
[36mDEBUG[0m:    [14-05-2024 21:35:56] Starting component Posthog
[36mDEBUG[0m:    [14-05-2024 21:35:56] Starting component LocalSegmentManager
[36mDEBUG[0m:    [14-05-2024 21:35:56] Starting component SegmentAPI
[32mINFO[0m:     [14-05-2024 21:35:56] Started server process [[36m53119[0m]
[32mINFO[0m:     [14-05-2024 21:35:56] Waiting for application startup.
[32mINFO[0m:     [14-05-2024 21:35:56] Application startup complete.
[32mINFO[0m:     [14-05-2024 21:35:56] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [14-05-2024 21:36:47] 127.0.0.1:62284 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [14-05-2024 21:36:47] 127.0.0.1:62284 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [14-05-2024 21:36:47] 127.0.0.1:62285 - "GET /api/v1/collections/entries?tenant=default_tenant&database=default_database HTTP/1.1" 200
[31mERROR[0m:    [14-05-2024 21:36:48] type object 'QueryEmbedding' has no attribute 'model_validate'
Traceback (most recent call last):
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/anyio/streams/memory.py", line 97, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/anyio/streams/memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/anyio/streams/memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 961, in get_nearest_neighbors
    await to_thread.run_sync(
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 940, in process_query
    query = QueryEmbedding.model_validate(orjson.loads(raw_body))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'QueryEmbedding' has no attribute 'model_validate'
[32mINFO[0m:     [14-05-2024 21:36:48] 127.0.0.1:62285 - "POST /api/v1/collections/f2737eea-4b24-4c05-8d38-5dcfeeb2bd9f/query HTTP/1.1" 500
[32mINFO[0m:     [14-05-2024 21:37:00] Shutting down
[32mINFO[0m:     [14-05-2024 21:37:01] Waiting for application shutdown.
[36mDEBUG[0m:    [14-05-2024 21:37:01] Stopping component System
[36mDEBUG[0m:    [14-05-2024 21:37:01] Stopping component SegmentAPI
[36mDEBUG[0m:    [14-05-2024 21:37:01] Stopping component LocalSegmentManager
[36mDEBUG[0m:    [14-05-2024 21:37:01] Stopping component Posthog
[36mDEBUG[0m:    [14-05-2024 21:37:01] Stopping component QuotaEnforcer
[36mDEBUG[0m:    [14-05-2024 21:37:01] Stopping component SqliteDB
[36mDEBUG[0m:    [14-05-2024 21:37:01] Stopping component OpenTelemetryClient
[32mINFO[0m:     [14-05-2024 21:37:01] Application shutdown complete.
[32mINFO[0m:     [14-05-2024 21:37:01] Finished server process [[36m53119[0m]
[32mINFO[0m:     [14-05-2024 21:43:05] Set chroma_server_nofile to 65535
[32mINFO[0m:     [14-05-2024 21:43:05] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [14-05-2024 21:43:05] Starting component System
[36mDEBUG[0m:    [14-05-2024 21:43:05] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [14-05-2024 21:43:05] Starting component SqliteDB
[36mDEBUG[0m:    [14-05-2024 21:43:05] Starting component QuotaEnforcer
[36mDEBUG[0m:    [14-05-2024 21:43:05] Starting component Posthog
[36mDEBUG[0m:    [14-05-2024 21:43:05] Starting component LocalSegmentManager
[36mDEBUG[0m:    [14-05-2024 21:43:05] Starting component SegmentAPI
[32mINFO[0m:     [14-05-2024 21:43:05] Started server process [[36m74442[0m]
[32mINFO[0m:     [14-05-2024 21:43:05] Waiting for application startup.
[32mINFO[0m:     [14-05-2024 21:43:05] Application startup complete.
[32mINFO[0m:     [14-05-2024 21:43:05] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [14-05-2024 21:43:11] 127.0.0.1:62386 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [14-05-2024 21:43:11] 127.0.0.1:62386 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [14-05-2024 21:43:11] 127.0.0.1:62387 - "GET /api/v1/collections/entries?tenant=default_tenant&database=default_database HTTP/1.1" 200
[31mERROR[0m:    [14-05-2024 21:43:12] type object 'QueryEmbedding' has no attribute 'model_validate'
Traceback (most recent call last):
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/anyio/streams/memory.py", line 97, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/anyio/streams/memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/anyio/streams/memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 961, in get_nearest_neighbors
    await to_thread.run_sync(
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 940, in process_query
    query = QueryEmbedding.model_validate(orjson.loads(raw_body))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'QueryEmbedding' has no attribute 'model_validate'
[32mINFO[0m:     [14-05-2024 21:43:13] 127.0.0.1:62387 - "POST /api/v1/collections/f2737eea-4b24-4c05-8d38-5dcfeeb2bd9f/query HTTP/1.1" 500
[32mINFO[0m:     [14-05-2024 21:43:19] 127.0.0.1:62395 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [14-05-2024 21:43:19] 127.0.0.1:62395 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [14-05-2024 21:43:19] 127.0.0.1:62396 - "GET /api/v1/collections/entries?tenant=default_tenant&database=default_database HTTP/1.1" 200
[31mERROR[0m:    [14-05-2024 21:43:21] type object 'QueryEmbedding' has no attribute 'model_validate'
Traceback (most recent call last):
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/anyio/streams/memory.py", line 97, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/anyio/streams/memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/anyio/streams/memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 961, in get_nearest_neighbors
    await to_thread.run_sync(
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jean.machado/miniconda3/envs/python312/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 940, in process_query
    query = QueryEmbedding.model_validate(orjson.loads(raw_body))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'QueryEmbedding' has no attribute 'model_validate'
[32mINFO[0m:     [14-05-2024 21:43:21] 127.0.0.1:62396 - "POST /api/v1/collections/f2737eea-4b24-4c05-8d38-5dcfeeb2bd9f/query HTTP/1.1" 500
[32mINFO[0m:     [14-05-2024 21:43:39] Shutting down
[32mINFO[0m:     [14-05-2024 21:43:39] Waiting for application shutdown.
[36mDEBUG[0m:    [14-05-2024 21:43:39] Stopping component System
[36mDEBUG[0m:    [14-05-2024 21:43:39] Stopping component SegmentAPI
[36mDEBUG[0m:    [14-05-2024 21:43:39] Stopping component LocalSegmentManager
[36mDEBUG[0m:    [14-05-2024 21:43:39] Stopping component Posthog
[36mDEBUG[0m:    [14-05-2024 21:43:39] Stopping component QuotaEnforcer
[36mDEBUG[0m:    [14-05-2024 21:43:39] Stopping component SqliteDB
[36mDEBUG[0m:    [14-05-2024 21:43:39] Stopping component OpenTelemetryClient
[32mINFO[0m:     [14-05-2024 21:43:39] Application shutdown complete.
[32mINFO[0m:     [14-05-2024 21:43:39] Finished server process [[36m74442[0m]
[32mINFO[0m:     [14-05-2024 21:44:02] Set chroma_server_nofile to 65535
[32mINFO[0m:     [14-05-2024 21:44:02] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [14-05-2024 21:44:02] Starting component System
[36mDEBUG[0m:    [14-05-2024 21:44:02] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [14-05-2024 21:44:02] Starting component SqliteDB
[36mDEBUG[0m:    [14-05-2024 21:44:02] Starting component QuotaEnforcer
[36mDEBUG[0m:    [14-05-2024 21:44:02] Starting component Posthog
[36mDEBUG[0m:    [14-05-2024 21:44:02] Starting component LocalSegmentManager
[36mDEBUG[0m:    [14-05-2024 21:44:02] Starting component SegmentAPI
[32mINFO[0m:     [14-05-2024 21:44:02] Started server process [[36m77313[0m]
[32mINFO[0m:     [14-05-2024 21:44:02] Waiting for application startup.
[32mINFO[0m:     [14-05-2024 21:44:02] Application startup complete.
[32mINFO[0m:     [14-05-2024 21:44:02] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [14-05-2024 21:44:03] Shutting down
[32mINFO[0m:     [14-05-2024 21:44:03] Waiting for application shutdown.
[36mDEBUG[0m:    [14-05-2024 21:44:03] Stopping component System
[36mDEBUG[0m:    [14-05-2024 21:44:03] Stopping component SegmentAPI
[36mDEBUG[0m:    [14-05-2024 21:44:03] Stopping component LocalSegmentManager
[36mDEBUG[0m:    [14-05-2024 21:44:03] Stopping component Posthog
[36mDEBUG[0m:    [14-05-2024 21:44:03] Stopping component QuotaEnforcer
[36mDEBUG[0m:    [14-05-2024 21:44:03] Stopping component SqliteDB
[36mDEBUG[0m:    [14-05-2024 21:44:03] Stopping component OpenTelemetryClient
[32mINFO[0m:     [14-05-2024 21:44:03] Application shutdown complete.
[32mINFO[0m:     [14-05-2024 21:44:03] Finished server process [[36m77313[0m]
